### ISSUE TITLE
Doesn't detect new files

### ISSUE THREAD

**Issue by tbredin** [StudioThick/opine-livereload#1]
I've noticed that adding a new file won't trigger a build (and also doesn't detect successive changes to this new file). Not sure why this is..
At the moment I get around this by restarting my watch each time I add a new file..

**Comment by mcccclean** [comment]
Ahh, yep, this is actually more of an issue with opine core rather than the livereload module. I've opened an issue over [there](https://github.com/StudioThick/gulp-opine/issues/1).
